spring:
  application:
    name: qiyu-live-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
    hikari:
      pool-name: qiyu-user-pool
      minimum-idle: 15
      maximum-pool-size: 300
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: 192.168.138.129
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
      password: 123456
qiyu:
  rmq:
    producer:
      nameSrv: 192.168.138.129:9876
      groupName: ${spring.application.name}
      retryTimes: 3
      sendTimeOut: 3000
    consumer:
      nameSrv: 192.168.138.129:9876
      groupName: ${spring.application.name}
dubbo:
  application:
    name: qiyu-live-user-provider
  registry:
    address: nacos://192.168.138.1:8848?namespace=qiyu-live-test&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: -1
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500



