server:
  servlet:
    context-path: /live/api
  port: 8081
spring:
  application:
    name: qiyu-live-api
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: qiyu-live-test