server:
  servlet:
    context-path: /live/api
  port: 8081
spring:
  application:
    name: qiyu-live-api
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: qiyu-live-test
  data:
    redis:
      port: 6379
      host: 192.168.138.129
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
      password: 123456